### PR TITLE
Remove docker-gc setup

### PR DESCRIPTION
**Pull request by puneetkatyal**
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/

### CODE REVIEW

**Comment by imkin** [comment]
How would we purge the existing static docker installation?

**Comment by mohitevishal** [comment]
We would also need to reload systemd once we purge the existing files. "Ad-hoc" play might help in this case :)

**Comment by puneetkatyal** [comment]
We do that using `Disable units` task in this role. I've added the following to `disabled_units` variable in `cluster.yml` --
```
          - static-docker.service
          - docker-gc.service
          - docker-gc.timer
```
For existing clusters, this approach only leaves a few harmless files in the installation directory that can be purged with an ad-hoc task and is cleaner for newer setups.

**Comment by imkin** [comment]
Needs rebase.

**Comment by puneetkatyal** [comment]
rebased.

**Review by mohitevishal — APPROVED** [review]
LGTM!

**Pull request merged**
